clean:	
	rm intSort strSort

intSort:	intSort_main.c intSort_funcs.c proj07_intList.h
	gcc -g -Wall -std=c99 intSort_main.c proj07_intList.h intSort_funcs.c -o intSort

strSort:	strSort_main.c strSort_funcs.c proj07_strList.h
	gcc -g -Wall -std=c99 strSort_main.c proj07_strList.h strSort_funcs.c -o strSort
